# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CityInformation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Malls',
            new_name='Mall',
        ),
        migrations.RenameModel(
            old_name='Parks',
            new_name='Museum',
        ),
        migrations.RenameModel(
            old_name='Museums',
            new_name='Park',
        ),
        migrations.RenameModel(
            old_name='Zoos',
            new_name='Restaurant',
        ),
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Zoo',
        ),
    ]
