# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityInformation', '0002_auto_20170929_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='museum',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='park',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='zoo',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
