# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityInformation', '0003_auto_20171027_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('emailAddress', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mall',
            name='image',
        ),
        migrations.RemoveField(
            model_name='museum',
            name='image',
        ),
        migrations.RemoveField(
            model_name='park',
            name='image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='zoo',
            name='image',
        ),
    ]
