# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityInformation', '0005_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('departments', models.TextField()),
                ('emailAddress', models.TextField()),
            ],
        ),
    ]
