# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityInformation', '0007_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='latitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='longitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='latitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='longitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='library',
            name='latitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='library',
            name='longitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mall',
            name='latitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mall',
            name='longitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='latitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='longitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='park',
            name='latitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='park',
            name='longitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zoo',
            name='latitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zoo',
            name='longitude',
            field=models.TextField(blank=True),
        ),
    ]
